'use client'
import React, { useState, useEffect } from 'react'
import Card from '@mui/material/Card'
import CardContent from '@mui/material/CardContent'
import Typography from '@mui/material/Typography'
import Divider from '@mui/material/Divider'
import { useRouter } from 'next/navigation'

export default function page() {

  const router = useRouter()

  const [Token, setToken] = useState('')

  useEffect(() => {
    // console.log(localStorage.getItem('accessToken'))
    if (!localStorage.getItem('accessToken')) {
      router.push('/login')
    }
    else {
      setToken(localStorage.getItem('accessToken'))
    }
  }, [])

  return (
    <div>
      {Token ? (<>
        <div>
          <Card>
            <CardContent>
              <Typography variant="h5" gutterBottom>
                Privacy Policy
              </Typography>
              <Divider className='mb-2' />
              <Typography variant="body1" gutterBottom>
                We want to inform users of this Service that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.
              </Typography>
              <Typography variant="h6" gutterBottom>
                Security
              </Typography>
              <Typography variant="body1" gutterBottom>
                We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.
              </Typography>
              <Typography variant="h6" gutterBottom>
                Links to Other Sites
              </Typography>
              <Typography variant="body1" gutterBottom>
                This Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us. Therefore, we strongly advise you to review the Privacy Policy of these websites. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
              </Typography>
              <Typography variant="h6" gutterBottom>
                Children’s Privacy
              </Typography>
              <Typography variant="body1" gutterBottom>
                These Services do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13. In the case we discover that a child under 13 has provided us with personal information, we immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do necessary actions.
              </Typography>
              <Typography variant="h6" gutterBottom>
                Changes to This Privacy Policy
              </Typography>
              <Typography variant="body1" gutterBottom>
                We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.
              </Typography>
              <Typography variant="h6" gutterBottom>
                Contact Us
              </Typography>
              <Typography variant="body1" gutterBottom>
                If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us.
              </Typography>
              <Typography variant="caption" gutterBottom>
                This privacy policy page was created at privacypolicytemplate.net and modified/generated by App Privacy Policy Generator
              </Typography>
            </CardContent>
          </Card>
        </div>
      </>) : (<>loading</>)}
    </div>
  )
}
